### ISSUE TITLE
What is this for? 

### ISSUE THREAD

**Issue by wbazant** [seekheart/coder_directory_api#31]
Hi, just stumbled upon this randomly. What is this project actually for? If it's an API does it run somewhere? If I have a google account, can I use it for something? It seems to try follow every possible best engineering practice - documents all the methods, says Mongo somewhere, you can run it from docker - but I don't know why, is it just like, a testing ground for software engineering practices?

**Comment by seekheart** [comment]
It's a pet project of mine to host information about coders. Thanks for visiting! 😄

**Comment by wbazant** [comment]
Cool! :D
